version: "3.3"

services:
  mkdocs:
    build: 
      context: ./
      dockerfile: ./Dockerfile_mkdocs
    image: eloco-wiki
    volumes:
      - .:/docs
    ports:
      - 8080:8000
  wikmd:
    build: 
      context: ./
      dockerfile: ./Dockerfile_wikmd
    container_name: wikmd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - HOMEPAGE=index.md #optional
      - HOMEPAGE_TITLE=index.md #optional
      - WIKMD_LOGGING=1 #optional
      - WIKI_DIRECTORY=/wiki
    ports:
      - 8080:5000
    restart: unless-stopped
    #volumes:
    #  - ./docs:/wiki
