version: "3.3"

services:
  wiki:
    build: .
    image: eloco-wiki
    volumes:
      - .:/docs
    ports:
      - 8080:8000
  #wikmd:
  #  build: wikmd/.
  #  container_name: wikmd
  #  ports:
  #    - 80:5000
  #  restart: unless-stopped
  #  volumes:
  #    - ./docs:/wiki
