version: "3.3"

services:
  mkdocs:
    container_name: eloco-wiki
    build: 
      context: ./
      dockerfile: ./Dockerfile_mkdocs
    image: eloco-wiki
    volumes:
      - .:/docs
    ports:
      - 12005:8000
  #wikmd:
  #  build: 
  #    context: ./
  #    dockerfile: ./Dockerfile_wikmd
  #  container_name: eloco-wikmd
  #  environment:
  #    - PUID=1000
  #    - PGID=1000
  #    - TZ=Asia/Shanghai
  #    - HOMEPAGE=index.md #optional
  #    - HOMEPAGE_TITLE=index.md #optional
  #    - WIKMD_LOGGING=1 #optional
  #    - WIKI_DIRECTORY=/wiki
  #    - WIKMD_PORT=5000
  #  ports:
  #    - 8081:5000
  #  restart: unless-stopped
    #volumes:
    #  - ./docs:/wiki
